import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "../providers/QueryProvider";
import { Toaster } from "sonner";
import { ConfirmProvider } from "@/components/ConfirmProvider"; // <-- thêm vào

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NeighborHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* Toast Notifications */}
        <Toaster position="top-center" richColors closeButton />

        {/* Confirm Modal dùng chung toàn app */}
        <ConfirmProvider>
          {/* React Query Provider */}
          <QueryProvider>{children}</QueryProvider>
        </ConfirmProvider>
      </body>
    </html>
  );
}
